### ISSUE TITLE
feat: Add a single-player mode

### ISSUE THREAD

**Issue by wakfi** [soitchu/Rubiks-Race-Multiplayer#1]
Two ways I see this. One could be a computer opponent, though that sounds difficult to get right. The other, more practical IMO option, would be to just have it be a non-competitive version of rubiks race. Kinda like just a dynamic slide puzzle. The player would just have to solve to match the assigned pattern, except there's no one that you're trying to "race" against. Perhaps it could be titled as a "training" mode.

**Comment by soitchu** [comment]
Done! Not going to lie, making a "CPU" opponent for the solo version seems quite tempting.
Anyway, let me know if you find any bugs! :D
