### ISSUE TITLE
Node dependency is not compatible with M1 Mac

### ISSUE THREAD

**Issue by wakfi** [soitchu/Rubiks-Race-Multiplayer#3]
It looks like this is coming from the dependency on `node`. Usually you don't need `node` in your project.json, it's usage is implied by either node-dependent packages (like express) or code for running a server in general.

<img width="850" alt="image" src="https://user-images.githubusercontent.com/55608093/167341533-d8ab7ec0-85cb-443b-95bd-6085d5e2749b.png">

**Comment by soitchu** [comment]
Done! Thank you for reviewing the code :)
